version: '3'
services:
    ide:
        build: .
        environment:
            DISPLAY: ${HOST_IP}:0
        tty: true
        stdin_open: true
        network_mode: host 
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
